/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-kepler-186-f-81a4b533cb2e426d85a17a3793a9420e
Title: Pixel Planet Kepler-186-f
*/

import * as THREE from 'three'
import { a } from "@react-spring/three";
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

import kepler186fScene from "../assets/3d/kepler-186f.glb";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshBasicMaterial
  }
}
type PlanetProps = {
    position: [number, number, number];
    scale: [number, number, number];
    rotation: [number, number, number];
};

export function KeplerPlanet(props: PlanetProps): JSX.Element {
  const { nodes, materials } = useGLTF(kepler186fScene) as GLTFResult;
  return (
    <a.group {...props}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </a.group>
  )
}