/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-kepler-7b-c3f70609c3e64ae4b351f6de01a74cd0
Title: Pixel Planet Kepler-7b
*/

import * as THREE from 'three'
import { a } from "@react-spring/three";
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

import kepler7bScene from "../assets/3d/kepler-7b.glb";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshBasicMaterial
  }
}
type PlanetProps = {
    position: [number, number, number];
    scale: [number, number, number];
    rotation: [number, number, number];
};

export function Kepler7b(props: PlanetProps): JSX.Element {
  const { nodes, materials } = useGLTF(kepler7bScene) as GLTFResult;
  return (
    <a.group {...props}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </a.group>
  )
}